(function(){
'use strict';
var config={FORM_ENDPOINT:'https://script.google.com/macros/s/AKfycbxohCKxEKOQZE7Yy4T53fcnSJxvNPo3ZrhK4z8-X8KcmTBdumYQgK4oqy5qRyZduSs1/exec',TURNSTILE_SITE_KEY:'0x4AAAAAAEUupCPuitD89Z6_',TURNSTILE_ACTION:'elg-workshop-registration'};
var form=document.getElementById('workshopForm');if(!form)return;
var params=new URLSearchParams(location.search);var token='';var draftKey='kryssen-workshop-registration-v2-1';
var status=document.getElementById('workshopStatus');var turnstileStatus=document.getElementById('workshopTurnstileStatus');
function track(name,data){if(typeof window.kryssenTrack==='function')return window.kryssenTrack(name,Object.assign({page:'workshop-v2'},data||{}));return false}
function set(id,value){var el=document.getElementById(id);if(el)el.value=value||''}
function nonce(){if(window.crypto&&window.crypto.randomUUID)return window.crypto.randomUUID().replace(/-/g,'');var a=new Uint8Array(16);if(window.crypto&&window.crypto.getRandomValues)window.crypto.getRandomValues(a);return Array.prototype.map.call(a,function(x){return x.toString(16).padStart(2,'0')}).join('')||String(Date.now())}
function cleanUrl(){var u=new URL(location.href);['submission','reference','message','field'].forEach(function(k){u.searchParams.delete(k)});history.replaceState({},'',u.pathname+(u.searchParams.toString()?'?'+u.searchParams.toString():''))}
function setupFields(){var base=location.origin+location.pathname;set('wsSourceUrl',location.href.slice(0,800));set('wsUtmSource',params.get('utm_source')||'');set('wsUtmMedium',params.get('utm_medium')||'');set('wsUtmContent',params.get('utm_content')||'');set('wsSuccessUrl',base);set('wsFailureUrl',base);set('wsFormStartedAt',String(Date.now()));set('wsSubmissionNonce',nonce())}
function saveDraft(){var data={};form.querySelectorAll('input,select').forEach(function(el){if(!el.name||el.type==='hidden'||el.name==='cf-turnstile-response'||el.name==='kryssen_guard_field')return;data[el.name]=el.type==='checkbox'?el.checked:el.value});try{sessionStorage.setItem(draftKey,JSON.stringify(data))}catch(e){}}
function restoreDraft(){var data=null;try{data=JSON.parse(sessionStorage.getItem(draftKey)||'null')}catch(e){}if(!data)return;form.querySelectorAll('input,select').forEach(function(el){if(!el.name||!Object.prototype.hasOwnProperty.call(data,el.name))return;if(el.type==='checkbox')el.checked=Boolean(data[el.name]);else el.value=data[el.name]})}
function clearDraft(){try{sessionStorage.removeItem(draftKey)}catch(e){}}
function showSuccess(reference){var name=(document.getElementById('wsName').value||'').trim();var done=document.getElementById('workshopDone');form.hidden=true;done.hidden=false;if(name)document.getElementById('wsWho').textContent=', '+name.split(' ')[0];done.querySelector('p').textContent='We have received your workshop registration.'+(reference?' Reference: '+reference+'.':'');done.focus();done.scrollIntoView({behavior:'smooth',block:'center'});clearDraft();cleanUrl();track('workshop_registration_submitted',{reference:reference||'recorded'});track('generate_lead',{form:'workshop_registration',reference:reference||'recorded'})}
function showFieldError(field){if(!field)return;var el=form.querySelector('[name="'+CSS.escape(field)+'"]');if(el){el.setAttribute('aria-invalid','true');el.focus();el.scrollIntoView({behavior:'smooth',block:'center'})}else if(field==='turnstile'){turnstileStatus.textContent='Complete the security check and submit again.'}}
function handleReturn(){var state=params.get('submission');if(state==='success'){showSuccess(params.get('reference')||'');return true}if(state==='received'||state==='failed'){restoreDraft();status.textContent=params.get('message')||'We could not confirm your registration. Review the form and submit again.';showFieldError(params.get('field')||'');cleanUrl()}return false}
function setupTurnstile(){var started=Date.now();function attempt(){if(window.turnstile&&window.turnstile.render){window.turnstile.render('#workshopTurnstile',{sitekey:config.TURNSTILE_SITE_KEY,action:config.TURNSTILE_ACTION,callback:function(v){token=v;turnstileStatus.textContent='Security check complete.'},'expired-callback':function(){token='';turnstileStatus.textContent='Security check expired. Complete it again.'},'error-callback':function(){token='';turnstileStatus.textContent='Security check could not load. Refresh to retry.'}});return}if(Date.now()-started>12000){turnstileStatus.textContent='Security check took too long to load. Refresh to retry.';return}setTimeout(attempt,100)}attempt()}
function valid(){var ok=true;form.querySelectorAll('input,select').forEach(function(el){if(el.type==='hidden'||el.name==='kryssen_guard_field')return;if(!el.checkValidity()){ok=false;if(el.reportValidity)el.reportValidity()}});return ok}
form.addEventListener('focusin',function(){if(form.dataset.started)return;form.dataset.started='true';track('workshop_registration_form_started')});
form.addEventListener('submit',function(e){e.preventDefault();if(!valid())return;status.textContent='';if(!config.FORM_ENDPOINT){status.textContent='Submission is not connected. Contact info@kryssengrowth.com.';return}if(!token){status.textContent='Complete the security check before submitting.';return}saveDraft();form.action=config.FORM_ENDPOINT;form.method='post';var button=form.querySelector('button[type=submit]');button.disabled=true;button.textContent='Submitting securely…';track('workshop_registration_submit_started',{focus:form.querySelector('[name="workshop_focus"]').value});form.submit()});
setupFields();restoreDraft();var returned=handleReturn();if(!returned)setupTurnstile();track('workshop_registration_page_view');
})();
